options:
  image:
    type: string
    default: mongo:latest
    description: The docker image to install.
  port:
    type: int
    default: 27017
    description: Port
  replica-set:
    type: boolean
    default: false
    description: Boolean to set the replica-set
  replica-set-name:
    type: string
    default: rs0
    description: Replica set name
